name: 'segment_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

vars:
  segment:
    segment_page_views_table: "{{ ref('example_segment_pages') }}"

seeds:
  +quote_columns: false
